services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    ports:
      - 8802:8802
    command: [sh, -c, "npm run prime && npm run build && npm start"]
    env_file:
      - .env.development
    volumes:
      - .:/app:delegated
      - /app/node_modules