apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: https://vacars-config.azconfig.io
  target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData: 
      type: json
      key: azureProvided.json
  configuration:
    refresh:
      enabled: true
      interval: 1m
      monitoring:
        keyValues:
          - key: database_url
  auth:
    workloadIdentity:
      managedIdentityClientId: 329feccf-8003-4b7b-9b46-78f3d59de407