apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723348464474
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: acrworkflow1723348464474.azurecr.io/image-workflow-1723348464474:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: config_file
              value: /app/config/azureProvided.json
          ports:
            - containerPort: 80
      volumes:
        - name: config-volume 
          configMap: 
            name: configmap-created-by-appconfig-provider
